<?php

/**
 * @file
 * Contains generate_ajax_form.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 *  Implements hook_toolbar_alter().
 */
function generate_ajax_form_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (isset($form['#attributes']['class'][0])) {
  	if ($form['#attributes']['class'][0] == 'node-jeux-edit-form' OR $form['#attributes']['class'][0] == 'node-operations-edit-form' OR $form['#attributes']['class'][0] == 'node-recrutement-infos-edit-form') {
		$form['#attached']['library'][] = 'generate_ajax_form/form.tree';
    }
  }
}

/**
 * Implements hook_mail().
 */
function generate_ajax_form_mail($key, &$message, $params) {
	$options = array(
		'langcode' => $message['langcode'],
	);

	switch ($key) {
		case 'send-candidature':
		$candidat = json_decode($params['data']['value'], TRUE);
		$email = '';

		$view = '<table border=0>';
		foreach ($candidat as $field) {
			if ($field['type'] == 'file') {
				continue;
			} elseif ($field['type'] == 'email') {
				$email = $field['value'];
			}
			$view .= '<tr><td>'. $field['label'] .':</td><td>'. $field['value'] .'</td></tr>';
		}
		$view .= '</table>';
		
		$message['from'] = $email;
		$message['subject'] = 'Nouvelle Candidature: ' .utf8_encode($params['title']);
		$message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
		$message['params']['attachments'][] = $params['attachments'];
		$message['body'][] = $view;
		break;
	}
}